### ISSUE TITLE
Add filename to the results table output if specified?

### ISSUE THREAD

**Issue by mryechkin** [projectwallace/wallace-cli#109]
First off, thank you for this great tool!

I've started to use it, and have a question - or maybe a potential feature request?

I have several CSS files that I'm analyzing, and currently I'm doing that by running the CLI for each file separately, ie (in my `package.json`):

```json
"styles:analyze": "wallace dist/styles/index.css && wallace dist/styles/a.css && wallace dist/styles/b.css"
```

When I do this, it's not super clear to tell where in the output the results end for one file and begin for the other:
![Screenshot 2023-09-25 at 10 32 18 PM](https://github.com/projectwallace/wallace-cli/assets/5657181/8342f6ad-297f-49fa-a34c-604914d6ecbf)

Is there a way to add a header of some sort to the results table? It would be really nice if when passing a file path to analyze, that path (or at least the filename) would be added to the table. Or perhaps a way to specify a custom header via a flag?

Any thoughts or suggestions on something like that?

**Comment by bartveneman** [comment]
Interesting points! 

I don't necessarily think that it is a job for the CLI output to show the input path or filename, although we do know the path to the input file, so we could add it to the output. I'll think about it, because adding this brings it's own issues (show the full path, or just the filename? What if the path or filename is very long?)

Then you'd still want some spacing in between outputs, I think. I'm no bash expert, but I'd probably put a couple of `echo ""` in between to create that extra space.

**Comment by mryechkin** [comment]
Makes sense. Just thought I'd ask!

I think like you said I'll just have to rely on some bash commands to give it a bit more separation.

Thanks. Feel free to close this issue
